import React, { useState, useEffect } from 'react';
import { binAPI } from '../../services/api';
import { TrendingUp, RefreshCw, AlertTriangle, ShieldCheck, Clock } from 'lucide-react';

export const AdminPredictions = () => {
  const [bins, setBins] = useState([]);
  const [loading, setLoading] = useState(true);

  const fetchBins = async () => {
    try {
      const res = await binAPI.getAll();
      setBins(res.data);
    } catch (err) {
      console.error("Failed to load predictions:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchBins();
  }, []);

  return (
    <div className="space-y-6">
      
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 bg-white p-6 rounded-3xl border border-emerald-100 shadow-sm">
        <div>
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-teal-100 border border-teal-200 text-teal-800 text-xs font-semibold uppercase mb-1">
            <TrendingUp className="w-3.5 h-3.5" />
            Machine Learning Inference Stream • Bengaluru Metropolitan
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-[#12372A] font-serif">
            Bin Fill Predictions & Overflow Forecasting
          </h1>
          <p className="text-xs sm:text-sm text-slate-500 mt-1">
            Real-time inference generated by trained multi-output fill rate and overflow classification models.
          </p>
        </div>

        <button
          onClick={fetchBins}
          className="px-4 py-2.5 rounded-xl text-xs font-semibold bg-[#12372A] hover:bg-[#1b4332] text-white flex items-center gap-2 transition-colors shadow-sm shrink-0"
        >
          <RefreshCw className="w-3.5 h-3.5" />
          <span>Refresh Inference</span>
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {loading ? (
          <div className="col-span-3 p-12 text-center text-slate-400">Loading prediction stream...</div>
        ) : (
          bins.map((bin) => {
            const pred = bin.latest_prediction;
            const isHigh = pred?.risk_level === 'HIGH';
            const isMedium = pred?.risk_level === 'MEDIUM';

            return (
              <div
                key={bin.id}
                className="bg-white p-5 rounded-2xl border border-emerald-100 shadow-sm space-y-3 hover:border-emerald-300 transition-colors"
              >
                <div className="flex justify-between items-start gap-2">
                  <div>
                    <span className="font-mono text-xs font-bold text-slate-700 bg-slate-100 px-2 py-0.5 rounded border border-slate-200">
                      {bin.bin_code}
                    </span>
                    <h3 className="text-base font-bold text-slate-900 mt-1.5 font-serif">{bin.location_name}</h3>
                    <p className="text-xs text-slate-500">{bin.waste_type}</p>
                  </div>

                  <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase shrink-0 ${
                    isHigh ? 'bg-red-100 text-red-800 border border-red-200' :
                    isMedium ? 'bg-amber-100 text-amber-800 border border-amber-200' :
                    'bg-emerald-100 text-emerald-800 border border-emerald-200'
                  }`}>
                    {pred ? pred.risk_level : 'LOW'} RISK
                  </span>
                </div>

                {/* Horizon Grid */}
                <div className="grid grid-cols-3 gap-2 bg-[#f7faf7] p-3 rounded-xl border border-emerald-100/80 text-xs font-mono">
                  <div>
                    <span className="text-[10px] text-slate-400 block uppercase">Current</span>
                    <strong className="text-sm text-slate-900">{bin.current_fill}%</strong>
                  </div>
                  <div>
                    <span className="text-[10px] text-slate-400 block uppercase">Pred 6h</span>
                    <strong className="text-sm text-emerald-700">{pred ? `${pred.predicted_6h}%` : 'N/A'}</strong>
                  </div>
                  <div>
                    <span className="text-[10px] text-slate-400 block uppercase">Pred 12h</span>
                    <strong className="text-sm text-teal-700">{pred ? `${pred.predicted_12h}%` : 'N/A'}</strong>
                  </div>
                </div>

                <div className="flex justify-between items-center text-xs text-slate-600 pt-1">
                  <span>Overflow Probability:</span>
                  <strong className="font-mono text-slate-900 font-bold">
                    {pred ? `${(pred.overflow_probability * 100).toFixed(1)}%` : 'N/A'}
                  </strong>
                </div>

                <div className="text-[11px] text-slate-400 flex items-center gap-1 pt-1 border-t border-slate-100">
                  <Clock className="w-3 h-3 text-slate-400" />
                  <span>Predicted at: {pred ? new Date(pred.prediction_time).toLocaleTimeString() : 'N/A'}</span>
                </div>
              </div>
            );
          })
        )}
      </div>

    </div>
  );
};

export default AdminPredictions;
